import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import { Play } from "next/font/google";

const play = Play({ subsets: ["latin"], weight: ["400", "700"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black`}
      >
        <div className={`w-full flex flex-row bg-[#f9f7f7] ${play.className}`}>
          <>
            <div className="max-w-[250px] w-1/4 bg-green-500">
              <div className=""> <Sidebar /> </div>
            </div>
            <div className="mx-10 h-full w-3/4">
              <div className="mb-10">
                <Topbar />
              </div>
              <div className="mb-40">{children}</div>
              <div>
                <Footer />
              </div>
            </div>
          </>
        </div>
      </body>
    </html>
  );
}
